[package]
version = "1.2.5"
title = "Reticle II"
description="An example kit extension of a viewport reticle using omni.ui.scene."
authors=["Original Matias Codesal, further extension David Woolf"]
readme  = "docs/README.md"
changelog="docs/CHANGELOG.md"
repository = ""
category = "Rendering"
keywords = ["camera", "reticle", "viewport"]
preview_image = "data/preview.png"
icon = "icons/icon.png"


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.viewport.utility" = {}
"omni.ui.scene" = {}


# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "omni.example.reticle"
